version: '3.8'
services:
  docker-mysql:
    image: mysql:8.0
    container_name: docker-mysql
    hostname: docker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: visitorservice
    ports:
      - 3307:3306
  visitors-service:
    container_name: visitorslog
    depends_on:
      - docker-mysql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8080
    environment:
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_PASSWORD: dbpass
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/visitorservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    restart: on-failure
    links:
      - docker-mysql:docker-mysql
#    labels:
#      collect_logs_with_filebeat: "true"
#      decode_log_event_to_json_object: "true"

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
#    ports:
#      - 9200:9200
#    environment:
#      discovery.type: single-node
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.12.1
#    ports:
#      - 5601:5601
#    restart: on-failure
#    depends_on:
#      - elasticsearch
#  filebeat:
#    image: docker.elastic.co/beats/filebeat:7.12.1
#    volumes:
#      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
#      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs
#      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers
#    user: root                                                             # Allow access to log files and docker.sock
#    restart: on-failure